### 전체 조회
GET http://localhost:8080/api/payment/getAll

### ID로 조회
GET http://localhost:8080/api/payment/get/1


### 생성
POST http://localhost:8080/api/payment/post
Content-Type: application/json

{
"userId" : 1,
"franchiseName" : "test11",
"paymentAmount" : 10000,
"paymentStatus" : "N"
}


### 수정
PUT http://localhost:8080/api/payment/put
Content-Type: application/json

{
  "id" : 1,
  "paymentStatus" : "Y"
}


### ID로 삭제
DELETE http://localhost:8080/api/payment/delete/1

### 전체 삭제
DELETE http://localhost:8080/api/payment/deleteAll